### ISSUE TITLE
Windows does not display widget

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#321] opened 2019-03-21 15:49 UTC
Not sure if this is a bug or an env issue. But I am not getting any output in IE:

<img width="800" alt="Screen Shot 2019-03-21 at 11 15 20 AM" src="https://user-images.githubusercontent.com/4806877/54765098-4afe3d00-4bcf-11e9-8de8-d624753fafc1.png">

```
[IPKernelApp] ERROR | No such comm target registered: hv-extension-comm
[IPKernelApp] WARNING | No such comm: hv-extension-comm
[IPKernelApp] WARNING | No such comm: hv-extension-comm
```

```
(intake-gui) C:\Users\IEUser>conda list
# packages in environment at C:\Users\IEUser\Miniconda\envs\intake-gui:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.1.0dev10                 py_0    bokeh/label/dev
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.2           py37hb32ad35_1    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.8.0                      py_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
cryptography              2.5              py37h74b6da3_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py37hfa6e2cd_1001    conda-forge
dask                      1.1.4                      py_0    conda-forge
dask-core                 1.1.4                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               1.26.0                   py37_1    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
futures-compat            1.0                       py3_0    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
holoviews                 1.12.0a1                   py_0    pyviz/label/dev
hvplot                    0.4.0                      py_0    pyviz/label/dev
icu                       58.2                     vc14_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
intake                    0.4.3+50.g403ad11           dev_0    <develop>
intel-openmp              2019.1                      144
ipykernel                 5.1.0           py37h39e3cac_1002    conda-forge
ipython                   7.1.1           py37h39e3cac_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1           py37he980bc4_1002    conda-forge
libblas                   3.8.0                     4_mkl    conda-forge
libcblas                  3.8.0                     4_mkl    conda-forge
liblapack                 3.8.0                     4_mkl    conda-forge
libpng                    1.6.36            h7602738_1000    conda-forge
libsodium                 1.0.16            h2fa13f4_1001    conda-forge
libtiff                   4.0.10            h36446d0_1001    conda-forge
locket                    0.2.0                      py_2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.1            py37hfa6e2cd_0    conda-forge
matplotlib                3.0.3                    py37_0    conda-forge
matplotlib-base           3.0.3            py37h3e3dc42_0    conda-forge
mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge
mkl                       2019.1                      144
msgpack-numpy             0.4.4.2                    py_1    conda-forge
msgpack-python            0.6.1            py37he980bc4_0    conda-forge
msys2-conda-epoch         20160418                      1
nbconvert                 5.4.1                      py_2    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
notebook                  5.7.6                    py37_0    conda-forge
numpy                     1.16.2           py37h8078771_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.0.2r               hfa6e2cd_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py37h6538335_0    conda-forge
pandoc                    2.7.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
panel                     0.5.0a4                    py_0    pyviz/label/dev
param                     1.9.0a4                    py_0    pyviz/label/dev
parso                     0.3.4                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    5.4.1           py37h9a613e6_1000    conda-forge
pip                       19.0.3                   py37_0    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.1            py37hfa6e2cd_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyqt                      5.6.0           py37h764d66f_1008    conda-forge
pyrsistent                0.14.11          py37hfa6e2cd_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1             h9460c21_1003    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-snappy             0.5.4            py37hd25c944_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyviz_comms               0.7.1                      py_0    conda-forge
pywinpty                  0.5.5                 py37_1000    conda-forge
pyyaml                    5.1              py37hfa6e2cd_0    conda-forge
pyzmq                     18.0.1           py37he418aac_0    conda-forge
qt                        5.6.2                h2639256_8    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
requests                  2.21.0                py37_1000    conda-forge
ruamel                    1.0                      py37_0    conda-forge
ruamel.yaml               0.15.89          py37hfa6e2cd_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
sip                       4.18.1          py37h6538335_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snappy                    1.1.7             h6538335_1002    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.26.0            hfa6e2cd_1001    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.3.1                    py37_1    conda-forge
tk                        8.6.9             hfa6e2cd_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py37hfa6e2cd_1000    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zeromq                    4.2.5             he025d50_1006    conda-forge
zict                      0.1.4                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge
```

**Comment by philippjfr** [comment] 2019-03-21 15:56
Does it work when displaying the button a second time? Could be the same issue as https://github.com/pyviz/panel/issues/218?

**Comment by jsignell** [comment] 2019-03-21 15:58
This was in notebook

**Comment by philippjfr** [comment] 2019-03-21 15:59
I see, do you know if it works in JLab on IE?

**Comment by xavArtley** [comment] 2019-03-21 15:59
I have the same problem
I work with jupyter lab

**Comment by xavArtley** [comment] 2019-03-21 15:59
But in chrome

**Comment by philippjfr** [comment] 2019-03-21 16:00
I think it's very unlikely to be the same issue tbh, classic notebook and jlab are very different. Also could you report your jupyterlab_pyviz version @xavArtley?

**Comment by xavArtley** [comment] 2019-03-21 16:02
I rebuild with the last version of master and I tell you
I work with this commit which work for the moment
https://github.com/pyviz/panel/commit/18c71b690bb51e193f82381d7b192533d4b07f1d

**Comment by philippjfr** [comment] 2019-03-21 16:02
To be clear I'm asking about jupyterlab_pyviz, not panel.

**Comment by xavArtley** [comment] 2019-03-21 16:06
@pyviz/jupyterlab_pyviz v0.7.0 enabled  ok

**Comment by xavArtley** [comment] 2019-03-21 16:12
![image](https://user-images.githubusercontent.com/18531147/54766836-4dc35700-4bfc-11e9-8905-11c4cff6a80a.png)
Then I executed this
![image](https://user-images.githubusercontent.com/18531147/54766913-6f244300-4bfc-11e9-9105-d4189c0e4848.png)
And now all works
Since this morning I failed

**Comment by jsignell** [comment] 2019-03-21 16:14
What holoviews version do you have?

**Comment by jsignell** [comment] 2019-03-21 16:23
I just tried to get on master and when pip installing got:
```
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\IEUser\\AppData\\Local\\Temp\\pip-uninstall-0rg7tels\\panel.exe'
Consider using the `--user` option or check the permissions.
```

Then on `pn.extension()`:
```python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-c5b8983e2d62> in <module>
      1 import panel as pn
----> 2 pn.extension()

~\Miniconda\envs\intake-gui\lib\site-packages\param\parameterized.py in __new__(class_, *args, **params)
   2712         inst = class_.instance()
   2713         inst.param._set_name(class_.__name__)
-> 2714         return inst.__call__(*args,**params)
   2715 
   2716     def __call__(self,*args,**kw):

~\panel\panel\config.py in __call__(self, *args, **params)
    166             _JupyterCommManager.get_client_comm(self._process_comm_msg,
    167                                                 "hv-extension-comm")
--> 168         load_notebook(config.inline)
    169         self._loaded = True
    170 

~\panel\panel\io\notebook.py in load_notebook(inline, load_timeout)
    191 
    192     resources = INLINE if inline else CDN
--> 193     custom_models_js = bundle_all_models() or ""
    194 
    195     configs, requirements, exports = require_components()

~\Miniconda\envs\intake-gui\lib\site-packages\bokeh\util\compiler.py in bundle_all_models()
    345 def bundle_all_models():
    346     """Create a bundle of all models. """
--> 347     return bundle_models(None)
    348 
    349 #-----------------------------------------------------------------------------

~\Miniconda\envs\intake-gui\lib\site-packages\bokeh\util\compiler.py in bundle_models(models)
    336     if bundle is None:
    337         try:
--> 338             _bundle_cache[key] = bundle = _bundle_models(custom_models)
    339         except CompilationError as error:
    340             print("Compilation failed:", file=sys.stderr)

~\Miniconda\envs\intake-gui\lib\site-packages\bokeh\util\compiler.py in _bundle_models(custom_models)
    553     bundles = ["bokeh", "bokeh-api", "bokeh-widgets", "bokeh-tables", "bokeh-gl"]
    554     known_modules = set(sum([ read_json(name) for name in bundles ], []))
--> 555     custom_impls = _compile_models(custom_models)
    556 
    557     extra_modules = {}

~\Miniconda\envs\intake-gui\lib\site-packages\bokeh\util\compiler.py in _compile_models(custom_models)
    533         compiled = _CACHING_IMPLEMENTATION(model, impl)
    534         if compiled is None:
--> 535             compiled = nodejs_compile(impl.code, lang=impl.lang, file=impl.file)
    536 
    537         if "error" in compiled:

~\Miniconda\envs\intake-gui\lib\site-packages\bokeh\util\compiler.py in nodejs_compile(code, lang, file)
    109                    "Use JavaScript or TypeScript directly instead.")
    110     compilejs_script = join(bokehjs_dir, "js", "compiler.js")
--> 111     output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file, bokehjs_dir=bokehjs_dir))
    112     lines = output.split("\n")
    113     for i, line in enumerate(lines):

~\Miniconda\envs\intake-gui\lib\site-packages\bokeh\util\compiler.py in _run_nodejs(argv, input)
    480 
    481 def _run_nodejs(argv, input=None):
--> 482     return _run(_nodejs_path(), argv, input)
    483 
    484 def _run_npmjs(argv, input=None):

~\Miniconda\envs\intake-gui\lib\site-packages\bokeh\util\compiler.py in _nodejs_path()
    456     global _nodejs
    457     if _nodejs is None:
--> 458         _nodejs = _detect_nodejs()
    459     return _nodejs
    460 

~\Miniconda\envs\intake-gui\lib\site-packages\bokeh\util\compiler.py in _detect_nodejs()
    448     version = ".".join(map(str, nodejs_min_version))
    449     raise RuntimeError('node.js v%s or higher is needed to allow compilation of custom models ' % version +
--> 450                        '("conda install nodejs" or follow https://nodejs.org/en/download/)')
    451 
    452 _nodejs = None

RuntimeError: node.js v6.10.0 or higher is needed to allow compilation of custom models ("conda install nodejs" or follow https://nodejs.org/en/download/)

```

**Comment by xavArtley** [comment] 2019-03-21 16:44
(civa) G:\DISC_Project>pip list
Package                           Version
--------------------------------- -----------------------
alabaster                         0.7.11
appdirs                           1.4.3
asciiplotlib                      0.1.5
astroid                           2.1.0
atomicwrites                      1.1.5
attrs                             19.1.0
autopep8                          1.4.3
Babel                             2.6.0
backcall                          0.1.0
beautifulsoup4                    4.7.1
bleach                            3.1.0
bokeh                             1.1.0.dev10
boto                              2.49.0
Bottleneck                        1.2.1
bs4                               0.0.1
cefpython3                        66.0
certifi                           2018.4.16
cftime                            1.0.3.4
chardet                           3.0.4
choldate                          0.1.0
Click                             7.0
clickclick                        1.2.2
cloudpickle                       0.8.0
colorama                          0.4.1
colorcet                          1.0.1
colorio                           0.2.4
connexion                         2.2.0
coverage                          4.5.1
cplot                             0.1.1
cycler                            0.10.0
cyordereddict                     1.0.0
Cython                            0.28.1
dask                              1.1.4
datashader                        0.6.9
datashape                         0.5.2
decorator                         4.4.0
defusedxml                        0.5.0
diay                              0.1.3
distributed                       1.26.0
Django                            2.1.7
docutils                          0.14
entrypoints                       0.3
faber                             snapshot
fastfunc                          0.1.6
flake8                            3.7.7
Flask                             1.0.2
fuzzywuzzy                        0.17.0
h5py                              2.8.0rc1
HeapDict                          1.0.0
holoviews                         1.11.2
html5lib                          1.0.1
hvplot                            0.4.0
icalendar                         4.0.3
idna                              2.7
imagesize                         1.0.0
inflection                        0.3.1
ipydatawidgets                    4.0.0
ipykernel                         5.1.0
ipympl                            0.2.0
ipython                           7.3.0
ipython-genutils                  0.2.0
ipyvolume                         0.4.6
ipywebrtc                         0.3.0
ipywidgets                        7.2.0
isort                             4.3.4
itsdangerous                      1.1.0
jedi                              0.13.3
jep                               3.7.1
Jinja2                            2.10
JPype1                            0.6.2
jsonschema                        3.0.1
jupyter                           1.0.0
jupyter-client                    5.2.4
jupyter-console                   6.0.0
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.4.0
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        0.35.4
jupyterlab-latex                  0.4.1
jupyterlab-launcher               0.10.5
jupyterlab-server                 0.2.0
Kivy                              1.10.1
Kivy-Garden                       0.1.4
kiwisolver                        1.0.1
lazy-object-proxy                 1.3.1
line-profiler                     2.1.2
llvmlite                          0.28.0
locket                            0.2.0
lxml                              4.2.5
Markdown                          3.0.1
MarkupSafe                        1.1.1
matplotlib                        2.2.2
mccabe                            0.6.1
meshio                            2.3.3
meshplex                          0.8.0
meshzoo                           0.4.3
mistune                           0.8.4
mock                              2.0.0
more-itertools                    4.2.0
mpmath                            1.0.0
msgpack                           0.6.1
multipledispatch                  0.6.0
mysql-connector                   2.1.6
mysql-connector-python            8.0.15
nbconvert                         5.4.1
nbformat                          4.4.0
nbsphinx                          0.3.3
netCDF4                           1.4.2
networkx                          2.1
nose                              1.3.7
notebook                          5.7.4
numba                             0.42.0
numexpr                           2.6.9
numpy                             1.16.2
openapi-spec-validator            0.2.4
opencv-python                     4.0.0.21
optimesh                          0.4.3
Optunity                          1.1.1
orthopy                           0.5.3
packaging                         17.1
pandas                            0.22.0
pandoc                            1.0.2
pandocfilters                     1.4.2
panel                             0.5.0a4.post15+g40971d9
param                             1.9.0a4.post2+g4763c50
parambokeh                        0.2.3
parso                             0.3.4
partd                             0.3.9
patsy                             0.5.1
pbr                               5.1.3
pickleshare                       0.7.5
Pillow                            5.0.0
pip                               19.0.3
pip-upgrade-outdated              1.5
pipdate                           0.3.2
plotly                            3.7.0
pluggy                            0.6.0
ply                               3.11
prometheus-client                 0.6.0
prompt-toolkit                    2.0.9
protobuf                          3.6.1
pscript                           0.7.0
psutil                            5.5.0
ptvsd                             4.2.4
py                                1.5.3
pyaadict                          0.0.1
pybind11                          2.2.4
pycodestyle                       2.5.0
pycoralie                         0.4
pyct                              0.4.6
pydevd                            1.4.0
pydicom                           1.2.2
pyDOE                             0.3.8
pyflakes                          2.1.1
Pygments                          2.3.1
pylint                            2.2.2
pymostra                          0.0.1
pyparsing                         2.2.0
pyrsistent                        0.14.11
pyserial                          3.4
pytest                            3.6.2
pytest-cov                        2.5.1
pytest-html                       1.19.0
pytest-metadata                   1.7.0
python-dateutil                   2.8.0
python-Levenshtein                0.12.0
pythreejs                         2.0.2
pytz                              2018.3
pyusb                             1.0.2
PyVISA                            1.9.1
PyVISA-py                         0.3.1
pyviz-comms                       0.7.0
PyWavelets                        0.5.2
pywinpty                          0.5.5
PyYAML                            3.13
pyzmq                             18.0.1
qtconsole                         4.3.1
quadpy                            0.12.10
requests                          2.19.1
retrying                          1.3.3
rise                              5.4.1
SALib                             1.1.3
scikit-image                      0.14.2
scikit-learn                      0.20.2
scipy                             1.2.1
seaborn                           0.8.1
selenium                          3.141.0
Send2Trash                        1.5.0
setuptools                        40.8.0
Shapely                           1.6.4.post1
simplegeneric                     0.8.1
six                               1.12.0
smartypants                       2.0.1
snowballstemmer                   1.2.1
sortedcontainers                  2.1.0
soupsieve                         1.8
Sphinx                            1.7.5
sphinx-bootstrap-theme            0.6.5
sphinxcontrib-websupport          1.1.0
SQLAlchemy                        1.2.18
statsmodels                       0.9.0
swagger-spec-validator            2.4.3
sympy                             1.1.1
tblib                             1.3.2
terminado                         0.8.1
testpath                          0.3.1
toolz                             0.9.0
tornado                           5.1.1
traitlets                         4.3.2
traittypes                        0.2.1
typed-ast                         1.3.1
umap-learn                        0.3.7
urllib3                           1.23
voluptuous                        0.11.5
vtk                               8.1.2
wcwidth                           0.1.7
webencodings                      0.5.1
Werkzeug                          0.14.1
wheel                             0.30.0
widgetsnbextension                3.2.0
wrapt                             1.10.11
xarray                            0.11.3
yapf                              0.26.0
zict                              0.1.4

**Comment by xavArtley** [comment] 2019-03-21 16:45
I found the error in jupyterlab
```
[I 17:08:12.473 LabApp] Build is up to date
[I 17:08:12.822 LabApp] Kernel started: 7ef813d4-3dcd-423e-9b47-fc683f37365d
[I 17:08:13.229 LabApp] Kernel started: 8af4ce9f-d9e4-4923-b5b0-d329e5adb19f
[I 17:08:13.837 LabApp] Adapting to protocol v5.1 for kernel 7ef813d4-3dcd-423e-9b47-fc683f37365d
[I 17:08:13.838 LabApp] Adapting to protocol v5.1 for kernel 7ef813d4-3dcd-423e-9b47-fc683f37365d
[I 17:08:14.009 LabApp] Adapting to protocol v5.1 for kernel 8af4ce9f-d9e4-4923-b5b0-d329e5adb19f
[I 17:08:14.010 LabApp] Adapting to protocol v5.1 for kernel 8af4ce9f-d9e4-4923-b5b0-d329e5adb19f
[I 17:08:19.012 LabApp] Creating new notebook in /notebooks/test
[I 17:08:19.255 LabApp] Kernel started: f37cd5b2-be65-4410-a04f-d89e45055338
[I 17:08:20.289 LabApp] Adapting to protocol v5.1 for kernel f37cd5b2-be65-4410-a04f-d89e45055338
[W 17:08:50.646 LabApp] 404 GET /bokeh-gl.min.js.map (::1) 335.03ms referer=None
[W 17:08:50.657 LabApp] 404 GET /bokeh-gl.min.js.map (::1) 4.00ms referer=None
[W 17:09:42.924 LabApp] 404 GET /bokeh-gl.min.js.map (::1) 4.00ms referer=None
[I 17:10:07.190 LabApp] Starting buffering for f37cd5b2-be65-4410-a04f-d89e45055338:2fc0a15b-63bf-4cf4-9421-5351dcb239c4
[I 17:10:07.926 LabApp] Kernel restarted: f37cd5b2-be65-4410-a04f-d89e45055338
[I 17:10:08.973 LabApp] Adapting to protocol v5.1 for kernel f37cd5b2-be65-4410-a04f-d89e45055338
[I 17:10:08.974 LabApp] Restoring connection for f37cd5b2-be65-4410-a04f-d89e45055338:2fc0a15b-63bf-4cf4-9421-5351dcb239c4
[I 17:10:08.975 LabApp] Replaying 5 buffered messages
[IPKernelApp] ERROR | No such comm target registered: hv-extension-comm
[W 17:10:17.303 LabApp] 404 GET /bokeh-gl.min.js.map (::1) 3.00ms referer=None
```

**Comment by philippjfr** [comment] 2019-03-21 16:46
@xavArtley Could you update to ``pyviz_comms 0.7.1``?

**Comment by jsignell** [comment] 2019-03-21 16:47
Also there is a newer holoviews at pyviz/label/dev

**Comment by jsignell** [comment] 2019-03-21 16:47
```
Using c:\users\ieuser\miniconda\envs\intake-gui\lib\site-packages
Searching for Markdown==2.6.11
Best match: Markdown 2.6.11
Adding Markdown 2.6.11 to easy-install.pth file
Installing markdown_py-script.py script to C:\Users\IEUser\Miniconda\envs\intake-gui\Scripts
Installing markdown_py.exe script to C:\Users\IEUser\Miniconda\envs\intake-gui\Scripts
error: [WinError 5] Access is denied: 'C:\\Users\\IEUser\\Miniconda\\envs\\intake-gui\\Scripts\\markdown_py.exe'
```

**Comment by jsignell** [comment] 2019-03-21 16:51
I still can't see panel output either. This is on latest panel now.

**Comment by philippjfr** [comment] 2019-03-21 16:52
I think you two are reporting two very different issues, I think the Windows issue is the same as this one: https://github.com/pyviz/holoviews/issues/3103

While @xavArtley's issue was a transient issue which occurred with pyviz_comms <=0.7.0 but was fixed in 0.7.1.

**Comment by xavArtley** [comment] 2019-03-21 16:53
with pyviz_comms 0.7.1
![image](https://user-images.githubusercontent.com/18531147/54769730-1f487a80-4c02-11e9-92cc-8ff2bcc43829.png)

**Comment by philippjfr** [comment] 2019-03-21 16:54
Make sure to clear all notebooks and reload the page before doing any testing.

**Comment by jsignell** [comment] 2019-03-21 16:54
@xavArtley did you update holoviews as well?

**Comment by xavArtley** [comment] 2019-03-21 17:09
I update holoviews to v1.12.0a1
I rebuild my jupyterlab extensions
I clean my notebook
I refresh with ctrl+F5
And I get always the same error

**Comment by xavArtley** [comment] 2019-03-21 17:10
```
[I 18:07:43.511 LabApp] Build is up to date
[I 18:07:47.371 LabApp] Kernel started: 671909c1-8497-4813-a907-8ced1788d48c
[I 18:07:47.691 LabApp] Kernel started: 1f77c645-507a-49da-a78c-0f59856b7a26
[I 18:07:48.316 LabApp] Kernel started: f5c78244-cbe5-46bb-84b6-cb83b46edaf3
[I 18:07:48.395 LabApp] Adapting to protocol v5.1 for kernel 671909c1-8497-4813-a907-8ced1788d48c
[I 18:07:48.397 LabApp] Adapting to protocol v5.1 for kernel 671909c1-8497-4813-a907-8ced1788d48c
[I 18:07:48.964 LabApp] Adapting to protocol v5.1 for kernel 1f77c645-507a-49da-a78c-0f59856b7a26
[I 18:07:48.965 LabApp] Adapting to protocol v5.1 for kernel 1f77c645-507a-49da-a78c-0f59856b7a26
[I 18:07:49.115 LabApp] Adapting to protocol v5.1 for kernel f5c78244-cbe5-46bb-84b6-cb83b46edaf3
[I 18:07:49.116 LabApp] Adapting to protocol v5.1 for kernel f5c78244-cbe5-46bb-84b6-cb83b46edaf3
[IPKernelApp] ERROR | No such comm target registered: hv-extension-comm
[IPKernelApp] WARNING | No such comm: 6d4f5990-11c3-41ba-bd65-f20fe72fd0d7
[IPKernelApp] WARNING | No such comm: 6d4f5990-11c3-41ba-bd65-f20fe72fd0d7
[IPKernelApp] WARNING | No such comm: 6d4f5990-11c3-41ba-bd65-f20fe72fd0d7
[I 18:07:55.108 LabApp] Saving file at /notebooks/test/Untitled.ipynb
[I 18:07:56.712 LabApp] Starting buffering for 671909c1-8497-4813-a907-8ced1788d48c:b79bd091-fd88-4d66-8a28
[I 18:07:56.718 LabApp] Starting buffering for 1f77c645-507a-49da-a78c-0f59856b7a26:4a084c2d-1994-420a-8f4e
[I 18:07:56.718 LabApp] Starting buffering for f5c78244-cbe5-46bb-84b6-cb83b46edaf3:a35cafaf-bf84-4a29-8838
[I 18:07:58.811 LabApp] Node v11.11.0

[I 18:07:58.984 LabApp] Build is up to date
[I 18:07:59.162 LabApp] Adapting to protocol v5.1 for kernel 671909c1-8497-4813-a907-8ced1788d48c
[I 18:07:59.184 LabApp] Adapting to protocol v5.1 for kernel f5c78244-cbe5-46bb-84b6-cb83b46edaf3
[I 18:08:07.779 LabApp] Adapting to protocol v5.1 for kernel f5c78244-cbe5-46bb-84b6-cb83b46edaf3
```

**Comment by philippjfr** [comment] 2019-03-21 17:22
>I clean my notebook

You definitely cleaned all notebooks that are loaded on refresh right? I can't reproduce this at all.

**Comment by jsignell** [comment] 2019-03-21 17:22
and restarted the kernel?

**Comment by xavArtley** [comment] 2019-03-21 18:10
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18531147/54774870-00031a80-4c0d-11e9-9441-88b6491cdf21.gif)

**Comment by stonebig** [comment] 2019-03-21 19:06
not a Windows nor Jupyterlab issue
![image](https://user-images.githubusercontent.com/4312421/54778369-c0403100-4c14-11e9-8028-4f03b10c258c.png)

**Comment by xavArtley** [comment] 2019-03-21 19:27
Indeed I can't reproduce on my PC at home
but I don't have same versions of libraries node and python

**Comment by philippjfr** [comment] 2019-03-22 19:53
@xavArtley Thanks to @jsignell's sleuthing I think we figured out the issue and I've just released jupyterlab_pyviz 0.7.0, so it would be very helpful if you could upgrade and try to reproduce.

**Comment by xavArtley** [comment] 2019-03-22 20:00
I won't be able to reproduce before monday

Le ven. 22 mars 2019 à 20:53, Philipp Rudiger <notifications@github.com> a
écrit :

**Comment by philippjfr** [comment] 2019-03-23 21:40
After https://github.com/pyviz/panel/pull/327 we should not be fully compatible with Internet Explorer again.

**Closed by philippjfr** 2019-03-23 21:40 UTC
