### ISSUE TITLE
Non-dropdown Select (similar to MultiSelect, but max one selection)

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#539] opened 2019-07-18 22:03 UTC
![image](https://user-images.githubusercontent.com/15331990/61495230-38bdc100-a96d-11e9-9a15-d75ab3267c9b.png)

**Comment by jsignell** [comment] 2019-07-25 13:44
Duplicate of #255

**Closed by jsignell** 2019-07-25 13:44 UTC
