### ISSUE TITLE
Memory is not freed after app session is closed

### ISSUE THREAD

**Issue by gregmuellegger** [pyviz/panel#212] opened 2019-01-21 13:26 UTC
I'm showing a holoviews plot in the browser using `panel.holoviews.Holoviews(plot).server_doc()`. I expect that when closing a session (i.e. closing the browser tab or reloading the tab) should free up some memory that was allocated by the previous session.

However it seems that this is not the case for my scenario. The code I use is documented in https://github.com/ioam/holoviews/issues/3421

I additionaly added a cleanup callback, which seems to be called properly a few seconds after reloading the tab:
```
main().server_doc(
    title='Memory Test',
).on_session_destroyed(lambda s: print('cleanup', s))
```

Here is the log of the bokeh server:

```
2019-01-21 14:20:15,393 Starting Bokeh server with process id: 26156
2019-01-21 14:20:16,395 [pid 26156] Memory usage: 62.00 MB (RSS), 520.00 MB (VMS)
2019-01-21 14:20:17,396 [pid 26156] Memory usage: 62.00 MB (RSS), 520.00 MB (VMS)
2019-01-21 14:20:18,396 [pid 26156] Memory usage: 62.00 MB (RSS), 520.00 MB (VMS)
2019-01-21 14:20:19,418 200 GET /main (::1) 870.50ms
2019-01-21 14:20:19,419 [pid 26156] Memory usage: 91.00 MB (RSS), 550.00 MB (VMS)
2019-01-21 14:20:19,615 101 GET /main/ws?bokeh-protocol-version=1.0&bokeh-session-id=xgTgouMpMppOGd2NxgFkHDb7jf2KWyT8SdgA1Y8ucbam (::1) 0.99ms
2019-01-21 14:20:19,616 WebSocket connection opened
2019-01-21 14:20:19,617 ServerConnection created
2019-01-21 14:20:20,396 [pid 26156] Memory usage: 92.00 MB (RSS), 551.00 MB (VMS)
2019-01-21 14:20:21,399 [pid 26156] Memory usage: 92.00 MB (RSS), 551.00 MB (VMS)
2019-01-21 14:20:22,396 [pid 26156] Memory usage: 93.00 MB (RSS), 552.00 MB (VMS)
2019-01-21 14:20:23,395 [pid 26156] Memory usage: 93.00 MB (RSS), 552.00 MB (VMS)
2019-01-21 14:20:24,407 [pid 26156] Memory usage: 93.00 MB (RSS), 553.00 MB (VMS)
2019-01-21 14:20:25,399 [pid 26156] Memory usage: 94.00 MB (RSS), 553.00 MB (VMS)
2019-01-21 14:20:26,397 [pid 26156] Memory usage: 94.00 MB (RSS), 554.00 MB (VMS)
2019-01-21 14:20:27,395 [pid 26156] Memory usage: 95.00 MB (RSS), 554.00 MB (VMS)
2019-01-21 14:20:28,427 [pid 26156] Memory usage: 95.00 MB (RSS), 554.00 MB (VMS)
2019-01-21 14:20:29,396 [pid 26156] Memory usage: 96.00 MB (RSS), 555.00 MB (VMS)
2019-01-21 14:20:30,409 [pid 26156] Memory usage: 96.00 MB (RSS), 555.00 MB (VMS)
2019-01-21 14:20:31,396 [pid 26156] Memory usage: 96.00 MB (RSS), 555.00 MB (VMS)
2019-01-21 14:20:31,524 200 GET /main (::1) 74.47ms
2019-01-21 14:20:31,532 WebSocket connection closed: code=1001, reason=None
2019-01-21 14:20:31,663 101 GET /main/ws?bokeh-protocol-version=1.0&bokeh-session-id=8bbCSw22YqI8NZCF9jCcG3MLpx8qliJhCpuHsenJhKPr (::1) 1.06ms
2019-01-21 14:20:31,663 WebSocket connection opened
2019-01-21 14:20:31,664 ServerConnection created
2019-01-21 14:20:32,396 [pid 26156] Memory usage: 96.00 MB (RSS), 555.00 MB (VMS)
2019-01-21 14:20:33,395 [pid 26156] Memory usage: 96.00 MB (RSS), 555.00 MB (VMS)
2019-01-21 14:20:34,395 [pid 26156] Memory usage: 96.00 MB (RSS), 555.00 MB (VMS)
...
2019-01-21 14:20:48,395 [pid 26156] Memory usage: 98.00 MB (RSS), 557.00 MB (VMS)
2019-01-21 14:20:49,395 [pid 26156] Memory usage: 98.00 MB (RSS), 557.00 MB (VMS)
cleanup <bokeh.server.contexts.BokehSessionContext object at 0x7f371c939cc0>
2019-01-21 14:20:50,395 [pid 26156] Memory usage: 98.00 MB (RSS), 557.00 MB (VMS)
2019-01-21 14:20:51,395 [pid 26156] Memory usage: 98.00 MB (RSS), 557.00 MB (VMS)
```

This might be related to a memory leak in holoviews https://github.com/ioam/holoviews/issues/3421

I could assume that the memory allocated is all used up in (holoviews) modules that have been imported and then contain some sort of caches. I get to that assumption since instantiating a new session (the parts in the logs starting from `2019-01-21 14:20:31,663 WebSocket connection opened`) doesn't seem to up the memory usage.

**Comment by philippjfr** [comment] 2019-01-28 22:23
The issue is being handled in holoviews so I'll close this one.

**Closed by philippjfr** 2019-01-28 22:23 UTC
