### ISSUE TITLE
Batch update for parameter values

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#24] opened 2018-09-04 18:05 UTC
The reactivity that comes from watching parameter values is really helpful, but it causes problems when changing a lot of parameter values at once.  E.g. for this code:
```python
from time import sleep
import param, panel as pp
pp.extension()

defaults = dict(a=0.2, b=0.4, c=0.6, d=0.8)

class C(param.Parameterized):
    a = param.Magnitude(defaults["a"])
    b = param.Magnitude(defaults["b"])
    c = param.Magnitude(defaults["c"])
    d = param.Magnitude(defaults["d"])
    
    reset_ = param.Action(lambda x: x.reset())
    
    @param.depends('a', 'b', 'c', 'd')
    def view(self):
        sleep(1)
        return "<H2>"+str((self.a, self.b, self.c, self.d))+"</H2>"

    def reset(self):
        self.set_param(**defaults)

c=C(name="")
pp.Row(c,pp.Column("<H1>Current&nbsp;values:</H2>", c.view))
```

![image](https://user-images.githubusercontent.com/1695496/45048766-5c706500-b042-11e8-99ab-f47bf2e8b16d.png)

If I press the "Reset" button, it changes the four parameters one... by... one..., calling the view() function each time.  Here view() is just a sleep call, but in practice in my real code it's a lengthy computation to plot something complicated, which is where I noticed the issue.  Oddly, in my real code I also was able to watch the widget values update one by one, but here the widgets are failing to be updated by the reset call even though the parameter values have changed:

![image](https://user-images.githubusercontent.com/1695496/45049038-1071f000-b043-11e8-8015-33884655d89c.png)

Note: this code depends on https://github.com/pyviz/panel/pull/21 so that the view() return type is representable, but I saw the problems with other Pane types before that PR.

**Comment by philippjfr** [comment] 2018-09-04 18:06
Isn't this meant to be a param issue, that's assigned to either @ceball or @jlstevens ?

**Comment by philippjfr** [comment] 2018-09-04 18:11
To be clear I'm happy to leave this open since I will have to make use of the new capabilities that will be added to param here, but the majority of changes will happen at the param level.

**Comment by philippjfr** [comment] 2018-09-04 18:28
Currently you subscribe to a parameter change like this:

```
parameterized.param.watch(callback, 'parameter_a')
```

i.e. you supply a callback that gets executed when the 'parameter_a' changes. The signature for that callback must be:

```
def callback(change):
    ...
```

where ``change`` is a param change object which describes what attribute changed and what the old and new values for that parameter are. In order to be able to batch parameter updates and callbacks we need something like this:

```
parameterized.param.watch(callback, ['parameter_a', 'parameter_b')

def callback(*changes):
   ...
```

where ``changes`` would potentially be a list of change events, which can be processed together.

**Comment by jbednar** [comment] 2018-09-04 19:27
Presumably there would also need to be a mechanism to *set* parameters in batch, for such a callback with multiple changes ever to be generated?  Maybe the `param.set_params()` method would need to support that.

**Comment by jlstevens** [comment] 2018-09-04 19:34
I agree this needs changes at the param level but the issue is most clearly exposed when using ``panel``. Personally I think ``set_params`` is the right place to batch changes for watched parameters and ``param`` will need to generalize the sort of callbacks that can have ``watch`` set on them.

I am happy to work on this if I am assigned this task!

**Comment by philippjfr** [comment] 2018-10-03 13:48
Now implemented.

**Closed by philippjfr** 2018-10-03 13:48 UTC
