### ISSUE TITLE
Pane example with plotly 

### ISSUE THREAD

**Issue by rr5577** [pyviz/panel#108] opened 2018-10-19 10:57 UTC
I´ve tried to do the pane example, and while it works for the bokeh and matplotlib plots, the plotly part displays just the top part of the output (the toolbar):
![image](https://user-images.githubusercontent.com/31547476/47214178-74573a80-d39d-11e8-8338-1d6a4438d96e.png)

The plot seems to be there and saving it as png works:
![image](https://user-images.githubusercontent.com/31547476/47214513-74a40580-d39e-11e8-8a34-bd3a0e11bd05.png)

**Comment by philippjfr** [comment] 2018-10-19 12:19
>I´ve tried to do the pane example, and while it works for the bokeh and matplotlib plots, the plotly part displays just the top part of the output (the toolbar):

Thanks for reporting this, seems to be some regression in the notebook as it works fine in a deployed app.

>The layout example also fails for me:

I'll push a fix for this shortly, it's currently assuming a dev version of holoviews (if it is installed).

**Comment by rr5577** [comment] 2018-10-19 12:52
Sorry, i edited the layout part out, I had installed panel but not upgraded the rest of the pyviz packages. Layout example works fine now.

regarding the pane, it seems if I use only plotly plot(s), the output is bugged. If I use a Row layout and have both a bokeh and plotly plot, the output size seems better (bottom part of plotly is still missing):
![image](https://user-images.githubusercontent.com/31547476/47219247-9b6a3800-d3ae-11e8-943e-8d98c8f07bec.png)

**Comment by philippjfr** [comment] 2018-10-19 12:57
Merged a fix for the holoviews issue, will look at the plotly height issue in a bit.

**Comment by jbednar** [comment] 2018-10-19 13:17
In the meantime you can usually fix spacing issues by adding an object like `pn.Spacer(height=500)` to your Row.

**Comment by philippjfr** [comment] 2018-10-23 12:08
The sizing issues should now be addressed.

**Closed by philippjfr** 2018-10-23 12:08 UTC
