### ISSUE TITLE
Kill all running `.show()` instances?

### ISSUE THREAD

**Issue by kazimuth** [pyviz/panel#684] opened 2019-10-10 02:17 UTC
I'm using a slightly wacky setup (jupyter-mode in `emacs`) and I end up calling `Pane.show()` a lot. Is there an easy way to kill all previously-created `show()` servers without killing the whole process?

**Comment by a-recknagel** [comment] 2019-10-12 15:27
I opened #697, which should theoretically close this. Is there a test case I can run to make sure it works as intended?

**Closed** 2019-10-13 09:02 UTC
Labels: sprintable, type: enhancement
