### ISSUE TITLE
CrossSelector doesn't stretch

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#499] opened 2019-07-03 18:01 UTC
```
dirs_widget = pn.widgets.CrossSelector(
    name='Available Directories', value=[],
    options=['dir1', 'dir2'], sizing_mode='stretch_both')
dirs_input = pn.widgets.TextInput(
    name='dirs')

pn.WidgetBox(dirs_widget, dirs_input, sizing_mode='stretch_both')
```

![image](https://user-images.githubusercontent.com/15331990/60614509-dddb7580-9d81-11e9-99f4-1a66f6f32dc2.png)

Also the left/right margins for the <</>> buttons are uneven

**Comment by ahuang11** [comment] 2019-07-03 18:05
@jlstevens

**Comment by jlstevens** [comment] 2019-07-03 18:06
Thanks for filing this @ahuang11. Having a responsive width cross-selector this would also be helpful for one of my ongoing projects and I also noticed the problem with the uneven `<<` and `>>` button spacing.

**Comment by philippjfr** [comment] 2019-07-03 22:45
That issue with spacing seems to be a regression. The ``sizing_mode`` issue is not too surprising to me since the widget was implemented before the layout refactor.

**Comment by jlstevens** [comment] 2019-07-11 21:18
> The sizing_mode issue is not too surprising to me since the widget was implemented before the layout refactor.

Does that mean this should be relatively easy to fix? I am happy to use panel dev versions or even patch panel myself with a short diff if necessary...

**Comment by philippjfr** [comment] 2019-07-11 21:19
Shouldn't be too hard, it just needs to forward the sizing_mode parameters appropriately to the sub-widgets, i.e. the multi-select widgets should expand but the buttons shouldn't.

**Comment by jlstevens** [comment] 2019-10-21 20:51
I think this issue can now be closed given that #545 has been merged.

**Closed by jlstevens** 2019-10-21 20:51 UTC
Labels: type: bug
